---

notifications:
  email: false

language: python

env:
  - MOLECULE_VER=2.19.0 DEBUG=""
  - MOLECULE_VER=2.19.0 DEBUG="--debug"
  - MOLECULE_VER=2.18.0 DEBUG=""
  - MOLECULE_VER=2.18.0 DEBUG="--debug"
  - MOLECULE_VER=2.17.0 DEBUG=""
  - MOLECULE_VER=2.17.0 DEBUG="--debug"
  - MOLECULE_VER=2.16.0 DEBUG=""
  - MOLECULE_VER=2.16.0 DEBUG="--debug"

python: 3.6

services:
  - docker

install:
  - sudo apt-get update
  - sudo apt-get install -y python-pip libssl-dev
  - pip install docker-py ansible==2.7.5 molecule==${MOLECULE_VER}

script:
  - ansible --version && molecule --version
  - molecule $DEBUG --base-config ./molecule-base.yml test
